services:
  - type: web
    name: js-py
    env: node
    buildCommand: "npm install && cd backend && npm install && cd ../frontend && python -m venv venv && source venv/bin/activate && pip install -r requirements.txt && cd .."
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 3000
    plan: free
    disk:
      sizeGB: 1
